# Generated by Django 4.1.4 on 2023-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
