# Generated by Django 4.1.4 on 2023-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
