# Generated by Django 4.1.4 on 2023-01-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0002_equity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='price_difference',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equity',
            name='sector',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Health Care', 'Health Care'), ('Financials', 'Financials'), ('Information Technology', 'Information Technology'), ('Telecommunication Services', 'Telecommunication Services'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate')], default='Energy', max_length=50),
        ),
    ]
